import { App, Component, MarkdownRenderer, TFile } from "obsidian";

import type { PageBlock, Preview } from "./types.ts";

const IMAGE_EXTENSIONS = new Set(["png", "jpg", "jpeg", "webp", "gif", "avif", "svg"]);

export type Representation = "rendered" | "source";

/**
 * Right column: generated Markdown, page by page.
 *
 * Blockwise and not all at once, because `%%…%%` is Obsidian's comment syntax and
 * remains invisible in reading view. The page container is the anchor and is the same
 * in both view modes. The sync layer is agnostic to representation toggles.
 */
export class MarkdownColumn {
	readonly scrollEl: HTMLElement;

	private container: HTMLElement;
	private blocks = new Map<number, HTMLElement>();
	private renderChild: Component | null = null;
	private representation: Representation = "rendered";
	private editable = false;
	private preview: Preview | null = null;
	private file: TFile | null = null;
	private run = 0;

	/** Called when heights may have changed. */
	onMeasurementNeeded: (() => void) | null = null;
	/** Called when text in a block has been edited. */
	onChange: ((block: PageBlock, newText: string) => void) | null = null;
	/** Called when an editor field loses focus. */
	onFocusLost: (() => void) | null = null;

	constructor(
		private app: App,
		root: HTMLElement,
		private parent: Component,
		private readonly eagerLimit: () => number,
	) {
		this.scrollEl = root.createDiv({ cls: "ocr-md-scroll" });
		this.container = this.scrollEl.createDiv({
			cls: "ocr-md-inhalt markdown-rendered",
		});
	}

	elements(): Map<number, HTMLElement> {
		return this.blocks;
	}

	currentPreview(): Preview | null {
		return this.preview;
	}

	currentFile(): TFile | null {
		return this.file;
	}

	setRepresentation(value: Representation): void {
		if (this.representation === value) return;
		this.representation = value;
		void this.render();
	}

	currentRepresentation(): Representation {
		return this.representation;
	}

	setEditable(value: boolean): void {
		if (this.editable === value) return;
		this.editable = value;
		for (const ta of this.container.querySelectorAll<HTMLTextAreaElement>(
			"textarea.ocr-md-quelltext-editor",
		)) {
			ta.readOnly = !value;
			ta.toggleClass("ocr-md-quelltext-readonly", !value);
		}
	}

	isEditable(): boolean {
		return this.editable;
	}

	async open(
		file: TFile,
		preview: Preview,
		representation: Representation,
	): Promise<void> {
		this.file = file;
		this.preview = preview;
		this.representation = representation;
		await this.render();
	}

	clear(emptyText?: string): void {
		this.run++;
		this.renderChild?.unload();
		this.renderChild = null;
		this.blocks.clear();
		this.container.empty();
		this.preview = null;
		this.file = null;
		if (emptyText !== undefined) {
			this.container.createDiv({ cls: "ocr-leer", text: emptyText });
		}
	}

	private async render(): Promise<void> {
		const preview = this.preview;
		const file = this.file;
		if (preview === null || file === null) return;

		const run = ++this.run;
		this.renderChild?.unload();
		const child = new Component();
		this.parent.addChild(child);
		this.renderChild = child;

		this.blocks.clear();
		this.container.empty();

		if (preview.blocks.length === 0) {
			this.container.createDiv({
				cls: "ocr-leer",
				text:
					"No page markers found. Was this file generated by pdf2md.py? " +
					"Expected one line '%% p. n %%' (or '%% S. n %%') per page.",
			});
			return;
		}

		const eager = preview.blocks.length <= this.eagerLimit();
		if (!eager && this.representation === "rendered") {
			this.container.createDiv({
				cls: "ocr-leer ocr-md-hinweis",
				text:
					`${preview.blocks.length} pages — exceeding the limit of ${this.eagerLimit()}. ` +
					"Pages remain unrendered; 'Source' displays full text.",
			});
		}

		for (const block of preview.blocks) {
			const el = this.container.createDiv({ cls: "ocr-md-seite" });
			el.dataset["seite"] = String(block.pageNumber);
			this.buildHeader(el, block);
			const body = el.createDiv({ cls: "ocr-md-koerper" });
			this.blocks.set(block.pageNumber, el);

			if (this.representation === "source") {
				const textarea = body.createEl("textarea", {
					cls: "ocr-md-quelltext-editor",
					attr: {
						"aria-label": `Source code page ${block.pageNumber}`,
						spellcheck: "false",
					},
				});
				textarea.readOnly = !this.editable;
				textarea.toggleClass("ocr-md-quelltext-readonly", !this.editable);
				textarea.value = block.markdown;
				this.adjustHeight(textarea);

				textarea.addEventListener("input", () => {
					if (!this.editable) return;
					block.markdown = textarea.value;
					this.adjustHeight(textarea);
					this.onChange?.(block, textarea.value);
					this.onMeasurementNeeded?.();
				});

				textarea.addEventListener("blur", () => {
					this.onFocusLost?.();
				});
				continue;
			}
			if (!eager) {
				body.createDiv({ cls: "ocr-md-platzhalter", text: "…" });
				continue;
			}
			await MarkdownRenderer.render(
				this.app,
				block.markdown,
				body,
				file.path,
				child,
			);
			if (run !== this.run) return;
			this.fixEmbeds(body, file);
		}

		if (this.representation === "source") {
			window.requestAnimationFrame(() => {
				for (const ta of this.container.querySelectorAll<HTMLTextAreaElement>(
					"textarea.ocr-md-quelltext-editor",
				)) {
					this.adjustHeight(ta);
				}
				this.onMeasurementNeeded?.();
			});
		}

		this.onMeasurementNeeded?.();
	}

	private adjustHeight(textarea: HTMLTextAreaElement): void {
		const baseHeight = "auto";
		textarea.style.setProperty("--ocr-editor-hoehe", baseHeight);
		textarea.style.setProperty(
			"--ocr-editor-hoehe",
			`${Math.max(textarea.scrollHeight, 36)}px`,
		);
	}

	private buildHeader(el: HTMLElement, block: PageBlock): void {
		const header = el.createDiv({ cls: "ocr-md-seitenkopf" });
		header.createSpan({ cls: "ocr-md-seitenzahl", text: `p. ${block.pageNumber}` });
		if (block.origin !== undefined) {
			const badge = header.createSpan({
				cls: `ocr-badge ocr-badge-${block.origin}`,
				text:
					block.origin === "textlayer"
						? "Textlayer"
						: block.origin === "ocr"
							? "OCR"
							: "Diagram",
			});
			badge.setAttribute(
				"aria-label",
				block.origin === "textlayer"
					? "Preserved losslessly from textlayer"
					: block.origin === "ocr"
						? "Read by model — word errors possible"
						: "Embedded as page image, text in callout",
			);
		}
		if (block.layout !== undefined) {
			header.createSpan({ cls: "ocr-md-layout", text: block.layout });
		}
	}

	private fixEmbeds(root: HTMLElement, source: TFile): void {
		const placeholders = root.querySelectorAll<HTMLElement>(".internal-embed");
		for (let i = 0; i < placeholders.length; i++) {
			const span = placeholders[i];
			if (span === undefined) continue;
			if (span.hasClass("is-loaded") || span.querySelector("img") !== null) continue;
			const src = span.getAttribute("src");
			if (src === null || src.length === 0) continue;
			const target = this.app.metadataCache.getFirstLinkpathDest(src, source.path);
			if (target === null) {
				span.addClass("ocr-embed-fehlt");
				span.setText(`Image not found: ${src}`);
				continue;
			}
			if (!IMAGE_EXTENSIONS.has(target.extension.toLowerCase())) continue;
			span.empty();
			span.addClass("is-loaded");
			const img = span.createEl("img", { cls: "ocr-embed-bild" });
			img.src = this.app.vault.getResourcePath(target);
			img.alt = target.name;
			img.addEventListener("load", () => this.onMeasurementNeeded?.(), {
				once: true,
			});
		}
	}
}
