// Splits a .md generated by pdf2md.py into page blocks.
//
// Why split at all: `%%…%%` is Obsidian's comment syntax and is invisible in
// reading view (pdf2md.py main() page marker chose it precisely for this reason).
// In rendered Markdown there is NO DOM node at the marker to anchor scroll coupling.
// Solution: split at markers and render each block into its own container — the
// container is the anchor.
//
// Positive side effect: pdf2md.py appends footnote definitions per page.
// Blockwise rendering fixes collisions of identical footnote numbers across pages
// that a single-block render creates.
//
// Pure module: no imports from `obsidian` so it is testable without a running app.

import type { Origin, PageBlock, Preview } from "./types.ts";

/** `%% p. 7 %%`, `%% S. 7 %%`, `%% p. 7 | ocr | two-column @48% %%`.
 *  The extra part is optional so files from runs prior to the marker
 *  extension continue to work unchanged. */
const MARKER = /^%%\s*(?:S\.|p\.|P\.)\s*(\d+)\s*(?:\|(.*?))?\s*%%\s*$/i;

/** Line opening or closing a code block (``` or ~~~). */
const FENCE = /^\s{0,3}(`{3,}|~{3,})/;

/** `Source: [[raw/ZR/script.pdf]]` or `Quelle: [[…]]` — pdf2md.py main() source line. */
const SOURCE_LINK = /^(?:Source|Quelle):\s*\[\[([^\]|]+)(?:\|[^\]]*)?\]\]\s*$/i;

/** Flat `key: value` from YAML frontmatter.
 *
 *  Intentionally not a full YAML parser: pdf2md.py main() frontmatter writes
 *  exclusively flat scalars. In the plugin, `metadataCache.getFileCache()` is
 *  the better source anyway; this function serves testability and acts as a
 *  fallback if the cache has not processed a file yet. */
function readFrontmatter(lines: string[]): {
	data: Record<string, string>;
	rest: number;
} {
	if (lines[0]?.trim() !== "---") return { data: {}, rest: 0 };
	const data: Record<string, string> = {};
	for (let i = 1; i < lines.length; i++) {
		const line = lines[i];
		if (line === undefined) break;
		if (line.trim() === "---") return { data, rest: i + 1 };
		const colon = line.indexOf(":");
		if (colon <= 0) continue;
		const key = line.slice(0, colon).trim();
		let val = line.slice(colon + 1).trim();
		// pdf2md.py main() frontmatter writes `source-pdf` JSON-quoted.
		// If the path contains quotes, remove them here; a path with ':' breaks
		// frontmatter anyway — for that there is the Source link.
		if (
			(val.startsWith('"') && val.endsWith('"') && val.length > 1) ||
			(val.startsWith("'") && val.endsWith("'") && val.length > 1)
		) {
			val = val.slice(1, -1);
		}
		data[key] = val;
	}
	// No closing '---' — broken frontmatter, take nothing.
	return { data: {}, rest: 0 };
}

function parseExtra(extra: string | undefined): {
	origin?: Origin;
	layout?: string;
} {
	if (extra === undefined) return {};
	const parts = extra
		.split("|")
		.map((t) => t.trim())
		.filter((t) => t.length > 0);
	const first = parts[0];
	if (first === undefined) return {};
	let origin: Origin | undefined;
	if (first === "textlayer" || first === "ocr") {
		origin = first;
	} else if (first === "diagram" || first === "diagramm") {
		origin = "diagram";
	}
	if (!origin) {
		// Unknown extra: pass through as layout, do not guess origin.
		return { layout: parts.join(" | ") };
	}
	const layout = parts.slice(1).join(" | ");
	return {
		origin,
		...(layout.length > 0 ? { layout } : {}),
	};
}

/** Parses the source text of a preview file.
 *
 *  Markers inside a code block are not treated as page boundaries —
 *  OCR outputs often contain fenced blocks. */
export function parsePreview(sourceText: string): Preview {
	const lines = sourceText.split("\n");
	const { data: frontmatter, rest } = readFrontmatter(lines);

	const blocks: PageBlock[] = [];
	const preambleLines: string[] = [];
	let sourceFromLink: string | null = null;
	let firstMarkerLine = -1;

	let current: PageBlock | null = null;
	let collection: string[] = [];
	let inFence = false;
	let fenceChar = "";

	const finish = () => {
		if (current === null) return;
		current.markdown = collection.join("\n").trim();
		blocks.push(current);
		current = null;
		collection = [];
	};

	for (let i = rest; i < lines.length; i++) {
		const line = lines[i];
		if (line === undefined) continue;

		const fence = FENCE.exec(line);
		if (fence !== null && fence[1] !== undefined) {
			if (!inFence) {
				inFence = true;
				fenceChar = fence[1][0] ?? "`";
			} else if (fence[1][0] === fenceChar) {
				inFence = false;
			}
		}

		const match = inFence ? null : MARKER.exec(line);
		if (match !== null && match[1] !== undefined) {
			if (firstMarkerLine < 0) {
				firstMarkerLine = i;
			}
			finish();
			current = {
				pageNumber: Number.parseInt(match[1], 10),
				...parseExtra(match[2]),
				markerLine: line,
				markdown: "",
			};
			continue;
		}

		if (current === null) {
			const link = SOURCE_LINK.exec(line);
			if (link !== null && link[1] !== undefined && sourceFromLink === null) {
				sourceFromLink = link[1].trim();
				continue; // Source line is metadata, not preamble.
			}
			preambleLines.push(line);
		} else {
			collection.push(line);
		}
	}
	finish();

	const rawPreamble =
		firstMarkerLine >= 0
			? lines.slice(0, firstMarkerLine).join("\n")
			: sourceText;

	const sourceFromFrontmatter =
		frontmatter["source-pdf"] ?? frontmatter["quelle-pdf"];
	return {
		frontmatter,
		sourcePdf:
			sourceFromFrontmatter !== undefined && sourceFromFrontmatter.length > 0
				? sourceFromFrontmatter
				: sourceFromLink,
		preamble: preambleLines.join("\n").trim(),
		rawPreamble,
		blocks,
	};
}

export function buildMarker(block: PageBlock): string {
	const extra: string[] = [];
	if (block.origin !== undefined) extra.push(block.origin);
	if (block.layout !== undefined) extra.push(block.layout);
	if (extra.length > 0) {
		return `%% S. ${block.pageNumber} | ${extra.join(" | ")} %%`;
	}
	return `%% S. ${block.pageNumber} %%`;
}

/**
 * Re-assembles a Preview structure losslessly back into a Markdown document.
 */
export function buildPreview(preview: Preview): string {
	if (preview.blocks.length === 0) {
		return preview.rawPreamble ?? (preview.preamble.length > 0 ? preview.preamble + "\n" : "");
	}

	const parts: string[] = [];
	if (preview.rawPreamble !== undefined) {
		const preambleTrimmed = preview.rawPreamble.trimEnd();
		if (preambleTrimmed.length > 0) {
			parts.push(preambleTrimmed);
		}
	} else {
		// Fallback: construct preamble from frontmatter and source
		const headerParts: string[] = [];
		const fmKeys = Object.keys(preview.frontmatter);
		if (fmKeys.length > 0) {
			headerParts.push("---");
			for (const k of fmKeys) {
				headerParts.push(`${k}: ${preview.frontmatter[k]}`);
			}
			headerParts.push("---");
		}
		if (preview.sourcePdf !== null) {
			headerParts.push(`Quelle: [[${preview.sourcePdf}]]`);
		}
		if (preview.preamble.length > 0) {
			headerParts.push(preview.preamble);
		}
		if (headerParts.length > 0) {
			parts.push(headerParts.join("\n\n"));
		}
	}

	for (const block of preview.blocks) {
		const marker = block.markerLine ?? buildMarker(block);
		parts.push(
			block.markdown.length > 0 ? `${marker}\n\n${block.markdown}` : marker,
		);
	}

	return parts.join("\n\n") + "\n";
}

/** Number from frontmatter, `null` if missing or not a number. */
export function numberFromFrontmatter(
	frontmatter: Record<string, unknown>,
	key: string,
): number | null {
	const val = frontmatter[key];
	if (typeof val === "number") return Number.isFinite(val) ? val : null;
	if (typeof val !== "string") return null;
	const num = Number.parseInt(val.trim(), 10);
	return Number.isFinite(num) ? num : null;
}

/** Text from frontmatter, `null` if empty or missing. */
export function textFromFrontmatter(
	frontmatter: Record<string, unknown>,
	key: string,
): string | null {
	const val = frontmatter[key];
	if (typeof val !== "string") return null;
	const trimmed = val.trim();
	return trimmed.length > 0 ? trimmed : null;
}
